# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/isaac/Projects/websocket-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/isaac/Projects/websocket-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/isaac/Projects/websocket-cpp/CMakeFiles /home/isaac/Projects/websocket-cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/isaac/Projects/websocket-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WEB_SOCKET_SERVER_CPP

# Build rule for target.
WEB_SOCKET_SERVER_CPP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WEB_SOCKET_SERVER_CPP
.PHONY : WEB_SOCKET_SERVER_CPP

# fast build rule for target.
WEB_SOCKET_SERVER_CPP/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/build.make CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/build
.PHONY : WEB_SOCKET_SERVER_CPP/fast

Base64.o: Base64.cpp.o
.PHONY : Base64.o

# target to build an object file
Base64.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/build.make CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/Base64.cpp.o
.PHONY : Base64.cpp.o

Base64.i: Base64.cpp.i
.PHONY : Base64.i

# target to preprocess a source file
Base64.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/build.make CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/Base64.cpp.i
.PHONY : Base64.cpp.i

Base64.s: Base64.cpp.s
.PHONY : Base64.s

# target to generate assembly for a file
Base64.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/build.make CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/Base64.cpp.s
.PHONY : Base64.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/build.make CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/build.make CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/build.make CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/main.cpp.s
.PHONY : main.cpp.s

mem.o: mem.cpp.o
.PHONY : mem.o

# target to build an object file
mem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/build.make CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/mem.cpp.o
.PHONY : mem.cpp.o

mem.i: mem.cpp.i
.PHONY : mem.i

# target to preprocess a source file
mem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/build.make CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/mem.cpp.i
.PHONY : mem.cpp.i

mem.s: mem.cpp.s
.PHONY : mem.s

# target to generate assembly for a file
mem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/build.make CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/mem.cpp.s
.PHONY : mem.cpp.s

ws.o: ws.cpp.o
.PHONY : ws.o

# target to build an object file
ws.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/build.make CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/ws.cpp.o
.PHONY : ws.cpp.o

ws.i: ws.cpp.i
.PHONY : ws.i

# target to preprocess a source file
ws.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/build.make CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/ws.cpp.i
.PHONY : ws.cpp.i

ws.s: ws.cpp.s
.PHONY : ws.s

# target to generate assembly for a file
ws.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/build.make CMakeFiles/WEB_SOCKET_SERVER_CPP.dir/ws.cpp.s
.PHONY : ws.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... WEB_SOCKET_SERVER_CPP"
	@echo "... Base64.o"
	@echo "... Base64.i"
	@echo "... Base64.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mem.o"
	@echo "... mem.i"
	@echo "... mem.s"
	@echo "... ws.o"
	@echo "... ws.i"
	@echo "... ws.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

